# -*- coding: utf-8 -*-
"""
investment_report.py

Description:
    Generates a one-page AI investment report for any Yahoo Finance ticker:
    a Kronos price forecast with Monte-Carlo confidence bands, trend analysis,
    support/resistance levels, historical + forecast volatility, technical
    indicators (RSI, MACD, EMA50/EMA200), and a transparent bullish/bearish
    composite probability. Saved as both PDF and PNG.

    Kronos forecasts a single path per call; to get a distribution (needed for
    confidence intervals and the ensemble bullish/bearish probability) this
    script runs the model --ensemble_size times independently (each a fresh
    stochastic sample) and aggregates the resulting close-price paths.

Usage:
    python investment_report.py --ticker AAPL
    python investment_report.py --ticker SAP.DE --pred_len 60 --ensemble_size 12

Output:
    - ./outputs/report_<TICKER>.pdf
    - ./outputs/report_<TICKER>.png

DISCLAIMER: This report is generated by a machine-learning model for research
and educational purposes only. It is not financial advice.
"""

import os
import sys
import argparse

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from matplotlib.patches import FancyBboxPatch

sys.path.append("../")
from model import Kronos, KronosTokenizer, KronosPredictor
from prediction_yahoo_finance import fetch_yahoo_data, INTERVAL_TO_FREQ
import report_analysis as ta
import fundamentals as fnd

SAVE_DIR = "./outputs"
os.makedirs(SAVE_DIR, exist_ok=True)

# --- Palette (validated categorical + status colors, light surface) ---
C_SURFACE = "#fcfcfb"
C_INK = "#0b0b0b"
C_INK_SECONDARY = "#52514e"
C_MUTED = "#898781"
C_GRID = "#e1e0d9"
C_BASELINE = "#c3c2b7"
C_BLUE = "#2a78d6"
C_BLUE_300 = "#6da7ec"
C_BLUE_100 = "#cde2fb"
C_YELLOW = "#eda100"
C_VIOLET = "#4a3aa7"
C_ORANGE = "#eb6834"
C_GOOD = "#0ca30c"
C_CRITICAL = "#d03b3b"
C_WARNING = "#fab219"

VERDICT_COLOR = {"BULLISH": C_GOOD, "BEARISH": C_CRITICAL, "NEUTRAL / MIXED": C_WARNING}


def run_ensemble_forecast(predictor, x_df, x_timestamp, y_timestamp, pred_len, T, top_p,
                           ensemble_size):
    """Runs `ensemble_size` independent stochastic Kronos forecasts and stacks the close paths."""
    close_paths = []
    for i in range(ensemble_size):
        print(f"  ensemble run {i + 1}/{ensemble_size} ...")
        pred_df = predictor.predict(
            df=x_df, x_timestamp=x_timestamp, y_timestamp=y_timestamp, pred_len=pred_len,
            T=T, top_p=top_p, sample_count=1, verbose=False,
        )
        close_paths.append(pred_df["close"].values)
    return np.array(close_paths)  # shape (ensemble_size, pred_len)


def draw_fundamentals(ax_chart, ax_text, fund: dict):
    """Renders the multi-year revenue/net-income bar chart and the fundamentals key-value list."""
    ax_chart.set_facecolor(C_SURFACE)
    ax_text.axis("off")

    if fund.get("error") or not fund.get("yearly_history"):
        ax_chart.axis("off")
        ax_chart.text(0.5, 0.5, "No multi-year financials available", ha="center", va="center",
                       fontsize=9, color=C_MUTED, transform=ax_chart.transAxes)
    else:
        years = [row["year"] for row in fund["yearly_history"]]
        revenue = [row["revenue"] for row in fund["yearly_history"]]
        net_income = [row["net_income"] for row in fund["yearly_history"]]
        x = np.arange(len(years))
        width = 0.36
        bars_rev = ax_chart.bar(x - width / 2, revenue, width, color=C_BLUE, label="Revenue")
        bars_ni = ax_chart.bar(x + width / 2, net_income, width, color=C_VIOLET, label="Net income")
        for bars in (bars_rev, bars_ni):
            for b in bars:
                h = b.get_height()
                ax_chart.text(b.get_x() + b.get_width() / 2, h, fnd.fmt_money(h), rotation=90,
                               ha="center", va="bottom" if h >= 0 else "top", fontsize=6.8,
                               color=C_INK_SECONDARY)
        ax_chart.set_xticks(x)
        ax_chart.set_xticklabels(years, fontsize=8.5, color=C_MUTED)
        ax_chart.set_title("Revenue vs. net income (fiscal year)", fontsize=9.5, color=C_INK,
                            loc="left")
        ax_chart.axhline(0, color=C_BASELINE, linewidth=0.8)
        ax_chart.legend(loc="upper left", fontsize=7.5, frameon=False)
        ax_chart.grid(True, axis="y", color=C_GRID, linewidth=0.8)
        for spine in ["top", "right"]:
            ax_chart.spines[spine].set_visible(False)
        for spine in ["left", "bottom"]:
            ax_chart.spines[spine].set_color(C_BASELINE)
        ax_chart.tick_params(colors=C_MUTED, labelsize=8)
        ax_chart.set_yticklabels([])

    ax_text.text(0.0, 1.0, "Fundamentals", transform=ax_text.transAxes, fontsize=11,
                 fontweight="bold", color=C_INK, va="top")

    if fund.get("error"):
        ax_text.text(0.0, 0.88, fund["error"], transform=ax_text.transAxes, fontsize=9,
                     color=C_MUTED, va="top")
        return

    cur = fund.get("currency") or ""
    col1 = (
        f"Market cap:             {fnd.fmt_money(fund['market_cap'], cur)}\n"
        f"KGV / P/E (trailing):    {fnd.fmt_ratio(fund['trailing_pe'])}\n"
        f"KGV / P/E (forward):     {fnd.fmt_ratio(fund['forward_pe'])}\n"
        f"PEG ratio:               {fnd.fmt_ratio(fund['peg_ratio'])}\n"
        f"Price / Book:            {fnd.fmt_ratio(fund['price_to_book'])}\n"
        f"EV / EBITDA:             {fnd.fmt_ratio(fund['ev_to_ebitda'])}\n"
        f"Revenue growth (YoY):    {fnd.fmt_pct(fund['revenue_growth_yoy'])}\n"
        f"Earnings growth (YoY):   {fnd.fmt_pct(fund['earnings_growth_yoy'])}\n"
        f"Analyst target price:    "
        f"{'$%.2f' % fund['target_mean_price'] if fund['target_mean_price'] is not None else 'n/a'}\n"
        f"Analyst recommendation:  {fund['recommendation'] or 'n/a'}\n"
    )
    col2 = (
        f"Free cash flow:      {fnd.fmt_money(fund['free_cash_flow'], cur)}\n"
        f"Operating cash flow: {fnd.fmt_money(fund['operating_cash_flow'], cur)}\n"
        f"Total debt:          {fnd.fmt_money(fund['total_debt'], cur)}\n"
        f"Total cash:          {fnd.fmt_money(fund['total_cash'], cur)}\n"
        f"Net debt:            {fnd.fmt_money(fund['net_debt'], cur)}\n"
        f"Debt / Equity:       {fnd.fmt_ratio(fund['debt_to_equity'])}\n"
        f"Current / Quick ratio: {fnd.fmt_ratio(fund['current_ratio'])} / "
        f"{fnd.fmt_ratio(fund['quick_ratio'])}\n"
        f"Margins (Gross/Op/Net): {fnd.fmt_pct0(fund['gross_margin'])}/"
        f"{fnd.fmt_pct0(fund['operating_margin'])}/{fnd.fmt_pct0(fund['profit_margin'])}\n"
        f"ROE / ROA:           {fnd.fmt_pct(fund['return_on_equity'])} / "
        f"{fnd.fmt_pct(fund['return_on_assets'])}\n"
    )
    ax_text.text(0.0, 0.88, col1, transform=ax_text.transAxes, fontsize=8.2,
                 color=C_INK_SECONDARY, va="top", family="monospace", linespacing=1.65)
    ax_text.text(0.48, 0.88, col2, transform=ax_text.transAxes, fontsize=8.2,
                 color=C_INK_SECONDARY, va="top", family="monospace", linespacing=1.65)


def build_report_figure(ticker, df, lookback, y_timestamp, close_paths, ema50_s, ema200_s,
                         rsi_s, macd_s, signal_s, hist_s, support, resistance, hist_vol,
                         fcst_vol_pct, bullish_prob, verdict, components, weights, interval,
                         pred_len, fund):
    hist = df.iloc[-lookback:].reset_index(drop=True)
    last_close = float(hist["close"].iloc[-1])
    last_date = hist["date"].iloc[-1]

    mean_fc = close_paths.mean(axis=0)
    p5, p25, p75, p95 = np.percentile(close_paths, [5, 25, 75, 95], axis=0)
    final_mean = mean_fc[-1]
    final_p5, final_p95 = p5[-1], p95[-1]

    fig = plt.figure(figsize=(12, 19.5), facecolor=C_SURFACE)
    gs = GridSpec(7, 1, height_ratios=[0.4, 3.0, 0.7, 0.7, 0.7, 1.9, 2.0], hspace=0.6,
                  left=0.09, right=0.96, top=0.955, bottom=0.03)

    fig.suptitle(f"{ticker} — Kronos AI Investment Report", fontsize=20, fontweight="bold",
                 color=C_INK, x=0.09, ha="left", y=0.975)
    fig.text(0.09, 0.955,
              f"Generated {pd.Timestamp.now():%Y-%m-%d %H:%M} UTC  ·  Data through "
              f"{last_date:%Y-%m-%d}  ·  {interval} bars  ·  {len(close_paths)}-run Monte-Carlo forecast",
              fontsize=9.5, color=C_MUTED)

    # --- Verdict banner ---
    ax_banner = fig.add_subplot(gs[0])
    ax_banner.axis("off")
    color = VERDICT_COLOR[verdict]
    arrow = "▲" if verdict == "BULLISH" else ("▼" if verdict == "BEARISH" else "▬")
    ax_banner.add_patch(FancyBboxPatch((0, 0), 1, 1, transform=ax_banner.transAxes,
                                        boxstyle="round,pad=0,rounding_size=0.04",
                                        linewidth=0, facecolor=color, alpha=0.14))
    ax_banner.text(0.02, 0.5, f"{arrow}  {verdict}", transform=ax_banner.transAxes,
                    fontsize=17, fontweight="bold", color=color, va="center")
    ax_banner.text(0.98, 0.5, f"Composite bullish probability: {bullish_prob * 100:.0f}%",
                    transform=ax_banner.transAxes, fontsize=12, color=C_INK_SECONDARY,
                    va="center", ha="right")

    # --- Price panel ---
    ax_price = fig.add_subplot(gs[1])
    ax_price.plot(hist["date"], hist["close"], color=C_INK, linewidth=2, label="Historical close")
    ax_price.plot(hist["date"], ema50_s, color=C_YELLOW, linewidth=1.4, label="EMA50")
    ax_price.plot(hist["date"], ema200_s, color=C_VIOLET, linewidth=1.4, label="EMA200")

    ax_price.fill_between(y_timestamp, p5, p95, color=C_BLUE_100, alpha=0.9, linewidth=0,
                           label="90% confidence interval")
    ax_price.fill_between(y_timestamp, p25, p75, color=C_BLUE_300, alpha=0.85, linewidth=0,
                           label="50% confidence interval")
    ax_price.plot(y_timestamp, mean_fc, color=C_BLUE, linewidth=2, linestyle="--",
                   label="Forecast (ensemble mean)")

    # Headroom above the data so the legend (anchored top-left) never overlaps a price
    # series or a support/resistance label drawn near the top of the range.
    level_prices = [p for p, _ in support] + [p for p, _ in resistance]
    all_vals = np.concatenate([
        hist["close"].values, ema50_s.values, ema200_s.values, p5, p95,
        np.array(level_prices) if level_prices else np.array([]),
    ])
    y_min, y_max = float(np.nanmin(all_vals)), float(np.nanmax(all_vals))
    y_span = y_max - y_min
    ax_price.set_ylim(y_min - 0.05 * y_span, y_max + 0.22 * y_span)

    ax_price.axvline(last_date, color=C_BASELINE, linewidth=1, linestyle=":")
    ax_price.text(last_date, y_max + 0.02 * y_span, " forecast start", fontsize=8,
                   color=C_MUTED, va="bottom")

    for price, touches in support:
        ax_price.axhline(price, color=C_GOOD, linewidth=1, linestyle="--", alpha=0.7)
        ax_price.text(hist["date"].iloc[0], price, f" S ${price:,.2f}", fontsize=8,
                       color=C_GOOD, va="bottom")
    for price, touches in resistance:
        ax_price.axhline(price, color=C_CRITICAL, linewidth=1, linestyle="--", alpha=0.7)
        ax_price.text(hist["date"].iloc[0], price, f" R ${price:,.2f}", fontsize=8,
                       color=C_CRITICAL, va="bottom")

    ax_price.set_ylabel("Price", color=C_INK_SECONDARY, fontsize=10)
    ax_price.legend(loc="upper left", fontsize=8.5, frameon=False, ncol=3)
    ax_price.grid(True, color=C_GRID, linewidth=0.8)
    ax_price.set_facecolor(C_SURFACE)
    for spine in ["top", "right"]:
        ax_price.spines[spine].set_visible(False)
    for spine in ["left", "bottom"]:
        ax_price.spines[spine].set_color(C_BASELINE)
    ax_price.tick_params(colors=C_MUTED, labelsize=8.5)

    # --- Volume panel ---
    ax_vol = fig.add_subplot(gs[2], sharex=ax_price)
    ax_vol.bar(hist["date"], hist["volume"], color=C_MUTED, width=1.6, alpha=0.6)
    ax_vol.axvline(last_date, color=C_BASELINE, linewidth=1, linestyle=":")
    ax_vol.set_ylabel("Volume", color=C_INK_SECONDARY, fontsize=9)
    ax_vol.grid(True, color=C_GRID, linewidth=0.8)
    ax_vol.set_facecolor(C_SURFACE)
    for spine in ["top", "right"]:
        ax_vol.spines[spine].set_visible(False)
    for spine in ["left", "bottom"]:
        ax_vol.spines[spine].set_color(C_BASELINE)
    ax_vol.tick_params(colors=C_MUTED, labelsize=8)

    # --- RSI panel ---
    ax_rsi = fig.add_subplot(gs[3], sharex=ax_price)
    ax_rsi.plot(hist["date"], rsi_s, color=C_BLUE, linewidth=1.4)
    ax_rsi.axhline(70, color=C_CRITICAL, linewidth=0.8, linestyle="--", alpha=0.6)
    ax_rsi.axhline(30, color=C_GOOD, linewidth=0.8, linestyle="--", alpha=0.6)
    ax_rsi.set_ylim(0, 100)
    ax_rsi.set_ylabel("RSI(14)", color=C_INK_SECONDARY, fontsize=9)
    ax_rsi.grid(True, color=C_GRID, linewidth=0.8)
    ax_rsi.set_facecolor(C_SURFACE)
    for spine in ["top", "right"]:
        ax_rsi.spines[spine].set_visible(False)
    for spine in ["left", "bottom"]:
        ax_rsi.spines[spine].set_color(C_BASELINE)
    ax_rsi.tick_params(colors=C_MUTED, labelsize=8)

    # --- MACD panel ---
    ax_macd = fig.add_subplot(gs[4], sharex=ax_price)
    hist_colors = np.where(hist_s.values >= 0, C_GOOD, C_CRITICAL)
    ax_macd.bar(hist["date"], hist_s, color=hist_colors, width=1.6, alpha=0.5)
    ax_macd.plot(hist["date"], macd_s, color=C_BLUE, linewidth=1.3, label="MACD")
    ax_macd.plot(hist["date"], signal_s, color=C_ORANGE, linewidth=1.3, label="Signal")
    ax_macd.axhline(0, color=C_BASELINE, linewidth=0.8)
    ax_macd.set_ylabel("MACD", color=C_INK_SECONDARY, fontsize=9)
    ax_macd.legend(loc="upper left", fontsize=8, frameon=False, ncol=2)
    ax_macd.grid(True, color=C_GRID, linewidth=0.8)
    ax_macd.set_facecolor(C_SURFACE)
    for spine in ["top", "right"]:
        ax_macd.spines[spine].set_visible(False)
    for spine in ["left", "bottom"]:
        ax_macd.spines[spine].set_color(C_BASELINE)
    ax_macd.tick_params(colors=C_MUTED, labelsize=8)
    plt.setp(ax_macd.get_xticklabels(), rotation=20, ha="right")

    for ax in (ax_price, ax_vol, ax_rsi):
        plt.setp(ax.get_xticklabels(), visible=False)

    # --- Fundamentals panel ---
    gs_fund = gs[5].subgridspec(1, 2, width_ratios=[0.85, 1.5], wspace=0.25)
    ax_fund_chart = fig.add_subplot(gs_fund[0])
    ax_fund_text = fig.add_subplot(gs_fund[1])
    draw_fundamentals(ax_fund_chart, ax_fund_text, fund)

    # --- Summary panel ---
    ax_summary = fig.add_subplot(gs[6])
    ax_summary.axis("off")

    horizon_label = f"{pred_len} {interval} bars"
    trend_text = ta.describe_trend(last_close, ema50_s.iloc[-1], ema200_s.iloc[-1], final_mean,
                                    horizon_label)

    support_txt = ", ".join(f"${p:,.2f} ({t}x)" for p, t in support) or "none identified"
    resistance_txt = ", ".join(f"${p:,.2f} ({t}x)" for p, t in resistance) or "none identified"

    left_col = (
        f"Last close:            ${last_close:,.2f}  ({last_date:%Y-%m-%d})\n"
        f"Forecast ({horizon_label}):  ${final_mean:,.2f}  "
        f"(90% CI ${final_p5:,.2f} – ${final_p95:,.2f})\n"
        f"Support levels:         {support_txt}\n"
        f"Resistance levels:      {resistance_txt}\n"
        f"Historical volatility:  {hist_vol:.1f}% (annualized)\n"
        f"Forecast dispersion:    {fcst_vol_pct:.1f}% (std. dev. over horizon)\n"
        f"RSI(14):                {rsi_s.iloc[-1]:.1f}\n"
        f"MACD histogram:         {hist_s.iloc[-1]:+.3f}\n"
        f"EMA50 / EMA200:         ${ema50_s.iloc[-1]:,.2f} / ${ema200_s.iloc[-1]:,.2f}\n"
    )

    score_lines = "\n".join(
        f"  {name:<32s} {components[name] * 100:5.0f}%  (weight {weights[key]:.0%})"
        for name, key in zip(components.keys(), ["ensemble", "trend", "momentum", "rsi"])
    )

    ax_summary.text(0.0, 1.0, "Key metrics", transform=ax_summary.transAxes, fontsize=11,
                     fontweight="bold", color=C_INK, va="top")
    # Escape literal "$" -- matplotlib treats unescaped "$...$" pairs as mathtext, which
    # silently drops the currency symbols and mangles spacing when a block has 2+ of them.
    left_col = left_col.replace("$", r"\$")
    ax_summary.text(0.0, 0.90, left_col, transform=ax_summary.transAxes, fontsize=9.3,
                     color=C_INK_SECONDARY, va="top", family="monospace", linespacing=1.6)

    ax_summary.text(0.52, 1.0, "Trend analysis", transform=ax_summary.transAxes, fontsize=11,
                     fontweight="bold", color=C_INK, va="top")
    trend_text = trend_text.replace("$", r"\$")
    ax_summary.text(0.52, 0.90, trend_text, transform=ax_summary.transAxes, fontsize=9.3,
                     color=C_INK_SECONDARY, va="top", wrap=True)

    ax_summary.text(0.52, 0.46, "Bullish/bearish composite score", transform=ax_summary.transAxes,
                     fontsize=11, fontweight="bold", color=C_INK, va="top")
    ax_summary.text(0.52, 0.38, score_lines, transform=ax_summary.transAxes, fontsize=8.6,
                     color=C_INK_SECONDARY, va="top", family="monospace", linespacing=1.6)

    ax_summary.text(0.0, 0.06,
                     "Disclaimer: generated by a machine-learning model (Kronos) for research/"
                     "educational purposes only. Not financial advice; past performance and "
                     "model forecasts do not guarantee future results.",
                     transform=ax_summary.transAxes, fontsize=7.6, color=C_MUTED, va="top",
                     style="italic", wrap=True)

    fig.patch.set_facecolor(C_SURFACE)
    return fig


def generate_report(ticker, lookback, pred_len, range_, interval, tokenizer_name, model_name,
                     device, T, top_p, ensemble_size, sr_window, sr_tolerance, skip_fundamentals):
    print(f"Loading Kronos tokenizer:{tokenizer_name} model:{model_name} ...")
    tokenizer = KronosTokenizer.from_pretrained(tokenizer_name)
    model = Kronos.from_pretrained(model_name)
    predictor = KronosPredictor(model, tokenizer, device=device, max_context=max(512, lookback))

    df = fetch_yahoo_data(ticker, range_, interval)
    if len(df) < lookback:
        raise ValueError(f"Not enough history: got {len(df)} rows, need at least {lookback}. "
                          f"Try a larger --range.")

    if skip_fundamentals:
        fund = {"error": "Fundamentals skipped (--skip_fundamentals)"}
    else:
        print("Fetching fundamentals ...")
        fund = fnd.fetch_fundamentals(ticker)
        if fund.get("error"):
            print(f"  warning: {fund['error']}")

    x_df = df.iloc[-lookback:][["open", "high", "low", "close", "volume", "amount"]]
    x_timestamp = df.iloc[-lookback:]["date"].reset_index(drop=True)
    freq = INTERVAL_TO_FREQ.get(interval, "B")
    y_timestamp = pd.date_range(start=df["date"].iloc[-1], periods=pred_len + 1, freq=freq)[1:]

    print(f"Running {ensemble_size}-member Monte-Carlo ensemble forecast "
          f"({pred_len} steps each) ...")
    close_paths = run_ensemble_forecast(predictor, x_df, pd.Series(x_timestamp), pd.Series(y_timestamp),
                                         pred_len, T, top_p, ensemble_size)

    print("Computing technical indicators ...")
    ema50_full = ta.compute_ema(df["close"], 50)
    ema200_full = ta.compute_ema(df["close"], 200)
    rsi_full = ta.compute_rsi(df["close"], 14)
    macd_full, signal_full, hist_full = ta.compute_macd(df["close"])

    ema50_s = ema50_full.iloc[-lookback:].reset_index(drop=True)
    ema200_s = ema200_full.iloc[-lookback:].reset_index(drop=True)
    rsi_s = rsi_full.iloc[-lookback:].reset_index(drop=True)
    macd_s = macd_full.iloc[-lookback:].reset_index(drop=True)
    signal_s = signal_full.iloc[-lookback:].reset_index(drop=True)
    hist_s = hist_full.iloc[-lookback:].reset_index(drop=True)

    hist_vol = ta.historical_volatility(df["close"], interval)

    last_close = float(df["close"].iloc[-1])
    final_returns = close_paths[:, -1] / last_close - 1.0
    fcst_vol_pct = float(np.std(final_returns) * 100.0)
    p_ensemble_up = float(np.mean(close_paths[:, -1] > last_close))

    support, resistance = ta.find_support_resistance(
        df.iloc[-lookback:], window=sr_window, tolerance_pct=sr_tolerance, num_levels=2)

    bullish_prob, verdict, components, weights = ta.compute_bullish_probability(
        p_ensemble_up, ema50_s.iloc[-1], ema200_s.iloc[-1], last_close, hist_s.iloc[-1],
        rsi_s.iloc[-1])

    print(f"Verdict: {verdict}  (composite bullish probability {bullish_prob * 100:.0f}%)")

    fig = build_report_figure(
        ticker, df, lookback, y_timestamp, close_paths, ema50_s, ema200_s, rsi_s, macd_s,
        signal_s, hist_s, support, resistance, hist_vol, fcst_vol_pct, bullish_prob, verdict,
        components, weights, interval, pred_len, fund)

    png_path = os.path.join(SAVE_DIR, f"report_{ticker.replace('.', '_')}.png")
    pdf_path = os.path.join(SAVE_DIR, f"report_{ticker.replace('.', '_')}.pdf")
    fig.savefig(png_path, dpi=150, facecolor=fig.get_facecolor())
    fig.savefig(pdf_path, facecolor=fig.get_facecolor())
    plt.close(fig)
    print(f"Report saved: {png_path}")
    print(f"Report saved: {pdf_path}")
    return png_path, pdf_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Kronos AI investment report for any Yahoo Finance ticker")
    parser.add_argument("--ticker", type=str, required=True)
    parser.add_argument("--lookback", type=int, default=400)
    parser.add_argument("--pred_len", type=int, default=60)
    parser.add_argument("--range", type=str, default="2y", dest="range_")
    parser.add_argument("--interval", type=str, default="1d")
    parser.add_argument("--tokenizer", type=str, default="NeoQuasar/Kronos-Tokenizer-base")
    parser.add_argument("--model", type=str, default="NeoQuasar/Kronos-small")
    parser.add_argument("--device", type=str, default=None)
    parser.add_argument("--T", type=float, default=1.0)
    parser.add_argument("--top_p", type=float, default=0.9)
    parser.add_argument("--ensemble_size", type=int, default=10,
                         help="Independent stochastic forecast runs used to build the confidence "
                              "bands and the ensemble bullish/bearish probability")
    parser.add_argument("--sr_window", type=int, default=5, help="Swing pivot half-window for support/resistance")
    parser.add_argument("--sr_tolerance", type=float, default=0.015,
                         help="Relative price tolerance used to cluster support/resistance levels")
    parser.add_argument("--skip_fundamentals", action="store_true",
                         help="Skip the Yahoo Finance fundamentals lookup (KGV, growth, FCF, debt, ...)")
    args = parser.parse_args()

    generate_report(
        ticker=args.ticker, lookback=args.lookback, pred_len=args.pred_len, range_=args.range_,
        interval=args.interval, tokenizer_name=args.tokenizer, model_name=args.model,
        device=args.device, T=args.T, top_p=args.top_p, ensemble_size=args.ensemble_size,
        sr_window=args.sr_window, sr_tolerance=args.sr_tolerance,
        skip_fundamentals=args.skip_fundamentals,
    )
